name: cmake CI [release]

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: get dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++        
    - name: configure
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: cmake --build build
    - name: run
      run: ./build/json_example
